#!/usr/bin/env bash

set -Eeuo pipefail

. ./src/run
. ./src/semver
. ./src/stdio

# This is our main functionality, and exposes our public API as subcommands.
if [ -z "${1:-}" ]; then
    krab_stdio_alert "Missing subcommand."
    exit 2
fi
command=$1
shift
function="krab_$(echo "$command" | tr '-' '_')"
if ! type -t "$function" >/dev/null || [ ! "$(type -t "$function")" = 'function' ]; then
    exit 2
fi
$function "$@"
