#!/usr/bin/env bash

_krab_migrate_is_installed() {
    local installation_dir
    installation_dir="$1"

    # Check for an installation manifest.
    if [ -f "$installation_dir/installed_version" ]; then
        return 0
    fi

    return 1
}

_krab_migrate_all_versions() {
    local versions_dir
    versions_dir="$1"

    echo 0
    find "$versions_dir" -type f -print0 | xargs -0 --no-run-if-empty basename -a | sed -r "s/^([0-9]+)-.*/\1/"
}

_krab_migrate_current_version() {
    local versions_dir
    versions_dir="$1"

    if is_installed "$versions_dir"; then
        cat "$versions_dir/.krab/installed_version"
        return 0
    fi
    echo 0
}

_krab_migrate_latest_version() {
    local versions_dir
    versions_dir="$1"

    _krab_migrate_all_versions "$versions_dir" | tail -n 1
}

_krab_migrate_available_versions() {
    local versions_dir
    versions_dir="$1"

    local current
    current=$(_krab_migrate_current_version "$versions_dir")
    for version in $(_krab_migrate_all_versions "$versions_dir"); do
        if [[ "$version" -gt "$current" ]]; then
            echo "$version"
        fi
    done
}

_krab_migrate_install_usage() {
    cat <<'EOF'
Usage: $ krab migrate-install [OPTION]... [INSTALLATION_DIR] [VERSIONS_DIR]

INSTALLATION_DIR is the directory in which the installation is tracked.
VERSIONS_DIR is the directory that contains the upgrade versions.

OPTION is one or more of the following:
    -h  Show this message.
EOF
}

krab_migrate_install() {
    while getopts 'h' option; do
        case "$option" in
            h)
                _krab_migrate_install_usage
                exit 0
                ;;
            ?)
                _krab_migrate_install_usage
                exit 2
                ;;
        esac
    done
    shift "$((OPTIND-1))"

    local installation_dir
    installation_dir="$1"
    local versions_dir
    versions_dir="$2"

    if _krab_migrate_is_installed "$installation_dir"; then
        ./vendor/bin/krab stdio-alert 'The application has been installed already.'
        exit 2
    fi

    mkdir -p "$installation_dir"
    _krab_migrate_latest_version "$versions_dir" > "$installation_dir/installed_version"
}

_krab_migrate_upgrade_usage() {
    cat <<'EOF'
Usage: $ krab migrate-upgrade [OPTION]... [INSTALLATION_DIR] [VERSIONS_DIR]

INSTALLATION_DIR is the directory in which the installation is tracked.
VERSIONS_DIR is the directory that contains the upgrade versions.

OPTION is one or more of the following:
    -h  Show this message.
EOF
}

krab_migrate_upgrade() {
    while getopts 'h' option; do
        case "$option" in
            h)
                _krab_migrate_upgrade_usage
                exit 0
                ;;
            ?)
                _krab_migrate_upgrade_usage
                exit 2
                ;;
        esac
    done
    shift "$((OPTIND-1))"

    local installation_dir
    installation_dir="$1"
    local versions_dir
    versions_dir="$2"

    if ! _krab_migrate_is_installed; then
        ./vendor/bin/krab stdio-alert 'The application has not been installed yet.'
        exit 2
    fi
    while read -r version; do
        upgrade="$(ls ./upgrades/"$version"-*)"
        ./vendor/bin/krab stdio-inform "Running upgrade $upgrade..."
        $upgrade
        echo "$version" > ./data/.installed_version
    done < <(available_versions)
}