#!/usr/bin/env bash

_krab_migrate_all_versions() {
    local migrations_dir
    migrations_dir="$1"

    find "$migrations_dir" -type f -print0 | xargs -0 --no-run-if-empty basename -a | grep -E '^[0-9]+-.*' | sed -r "s/^([0-9]+)-.*/\1/" | sort -n
}

_krab_migrate_current_version() {
    local installation_dir
    installation_dir="$1"

    if [ -f "$installation_dir/installed_version" ]; then
        cat "$installation_dir/installed_version"
        return 0
    fi
    echo -1
}

_krab_migrate_latest_version() {
    local migrations_dir
    migrations_dir="$1"

    _krab_migrate_all_versions "$migrations_dir" | tail -n 1
}

_krab_migrate_available_versions() {
    local installation_dir
    installation_dir="$1"
    local migrations_dir
    migrations_dir="$2"

    local current
    current=$(_krab_migrate_current_version "$installation_dir")
    for version in $(_krab_migrate_all_versions "$migrations_dir"); do
        if [[ "$version" -gt "$current" ]]; then
            echo "$version"
        fi
    done
}

_krab_migrate_usage() {
    cat <<'EOF'
Usage: $ krab migrate-upgrade [OPTION]... [INSTALLATION_DIR] [MIGRATIONS_DIR]

INSTALLATION_DIR is the directory in which the installation is tracked.
MIGRATIONS_DIR is the directory that contains the upgrades.

OPTION is one or more of the following:
    -h  Show this message.
EOF
}

krab_migrate() {
    while getopts 'h' option; do
        case "$option" in
            h)
                _krab_migrate_usage
                exit 0
                ;;
            ?)
                _krab_migrate_usage
                exit 2
                ;;
        esac
    done
    shift "$((OPTIND-1))"

    local installation_dir
    installation_dir="$1"
    local migrations_dir
    migrations_dir="$2"

    mkdir -p "$installation_dir"

    local tasks=""
    while read -r version; do
        upgrade="$(ls "$migrations_dir/$version"-*)"
        tasks="$tasks$upgrade\0echo $version > $installation_dir/installed_version\0"
    done < <(_krab_migrate_available_versions "$installation_dir" "$migrations_dir")
    echo -en "$tasks" | xargs -0 bash -c 'krab_run "$@"' _
}