#!/usr/bin/env bash

function _krab_stdio_message {
    message=$1
    highlight=$(( $2 + 40))
    normal=$(( $2 + 30))
    printf "\n\033[0;%dm  \033[0;1;%dm %s\033[0m\n\n" "$highlight" "$normal" "$message"
}

function krab_stdio_state {
    message=$1
    _krab_stdio_message "$message" 7
}

function krab_stdio_inform {
    message=$1
    _krab_stdio_message "$message" 6
}

function krab_stdio_confirm {
    message=$1
    _krab_stdio_message "$message" 2
}

function krab_stdio_alert {
    message=$1
    _krab_stdio_message "$message" 1
}
