#!/usr/bin/env bash

function _krab_stdio_message {
    message=$1
    shade=$2
    printf "\n\033[0;4${shade}m  \033[0;1;3${shade}m ${message}\033[0m\n\n"
}

function krab_stdio_state {
    message=$1
    _krab_stdio_message "$message" 7
}

function krab_stdio_inform {
    message=$1
    _krab_stdio_message "$message" 6
}

function krab_stdio_confirm {
    message=$1
    _krab_stdio_message "$message" 2
}

function krab_stdio_alert {
    message=$1
    _krab_stdio_message "$message" 1
}
