#!/usr/bin/env bash

set -Euo pipefail

cd "$(dirname "$0")/../.." || exit

. ./tests/assert

test_migrate_without_upgrades() {
    local installation_dir
    installation_dir="$(mktemp -d)/.krab"
    local migrations_dir
    migrations_dir=$(mktemp -d)
    mkdir -p "$installation_dir"
    echo 0 > "$installation_dir/installed_version"
    ./bin/krab migrate "$installation_dir" "$migrations_dir" &>/dev/null
    assertEquals 0 "$?"
    rm -rf "$installation_dir"
    rm -rf "$migrations_dir"
}

test_migrate_with_upgrades_none_installed() {
    local installation_dir
    installation_dir="$(mktemp -d)/.krab"
    local migrations_dir
    migrations_dir=$(mktemp -d)
    output_file=$(mktemp)
    echo "echo FOO >> $output_file" > "$migrations_dir/001-foo"
    echo "echo BAR >> $output_file" > "$migrations_dir/1-bar"
    echo "echo BAZ >> $output_file" > "$migrations_dir/123-baz"
    echo "echo QUX >> $output_file" > "$migrations_dir/666-qux"
    chmod -R u+x $migrations_dir/*
    ./bin/krab migrate "$installation_dir" "$migrations_dir" &>/dev/null
    assertEquals '666' "$(cat "$installation_dir/installed_version")"
    assertEquals "$(printf 'FOO\nBAR\nBAZ\nQUX\n')" "$(cat "$output_file")"
    rm -rf "$installation_dir"
    rm -rf "$migrations_dir"
}

test_migrate_with_upgrades_some_installed() {
    local installation_dir
    installation_dir="$(mktemp -d)/.krab"
    local migrations_dir
    migrations_dir=$(mktemp -d)
    output_file=$(mktemp)
    mkdir -p "$installation_dir"
    echo 1 > "$installation_dir/installed_version"
    echo "echo FOO >> $output_file" > "$migrations_dir/001-foo"
    echo "echo BAR >> $output_file" > "$migrations_dir/1-bar"
    echo "echo BAZ >> $output_file" > "$migrations_dir/123-baz"
    echo "echo QUX >> $output_file" > "$migrations_dir/666-qux"
    chmod -R u+x $migrations_dir/*
    ./bin/krab migrate "$installation_dir" "$migrations_dir" &>/dev/null
    assertEquals '666' "$(cat "$installation_dir/installed_version")"
    assertEquals "$(printf 'BAZ\nQUX\n')" "$(cat "$output_file")"
    rm -rf "$installation_dir"
    rm -rf "$migrations_dir"
}

test_migrate_with_failed_upgrades() {
    local installation_dir
    installation_dir="$(mktemp -d)/.krab"
    local migrations_dir
    migrations_dir=$(mktemp -d)
    output_file=$(mktemp)
    mkdir -p "$installation_dir"
    echo 0 > "$installation_dir/installed_version"
    echo "echo FOO >> $output_file" > "$migrations_dir/001-foo"
    echo "echo BAR >> $output_file" > "$migrations_dir/1-bar"
    echo "exit 1" > "$migrations_dir/123-baz"
    echo "echo QUX >> $output_file" > "$migrations_dir/666-qux"
    chmod -R u+x $migrations_dir/*
    ./bin/krab migrate "$installation_dir" "$migrations_dir" &>/dev/null
    assertNotEquals 0 "$?"
    assertEquals '1' "$(cat "$installation_dir/installed_version")"
    assertEquals "$(printf 'FOO\nBAR\n')" "$(cat "$output_file")"
    rm -rf "$installation_dir"
    rm -rf "$migrations_dir"
}

test_migrate_common() {
    assert_command 'migrate'
}

. ./vendor/shunit2/shunit2