#!/usr/bin/env bash

set -Euo pipefail

cd "$(dirname "$0")/.." || exit

. ./tests/assert

test_krab_common() {
    assert_command ''
}

test_krab_arbitrary_pwd() {
    local krab_dir
    krab_dir=$(pwd)
    pushd "$(mktemp -d)" || return
    eval "$krab_dir/bin/krab -h" &>/dev/null
    assertEquals 0 "$?"
    popd || return
}

. ./vendor/shunit2/shunit2
