#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

shellcheck -x ./krab
directories='./bin ./tests'
for directory in $directories; do
    find "$directory" | while read -r file; do
        if [ ! -f "$file" ]; then
            continue
         fi
        shellcheck -x "$file"
    done
done
