#!/usr/bin/env bash

cd "$(dirname "$0")/.." || exit

test_state() {
    actual="$(./krab stdio-state 'Hi, there!' 2>&1 > /dev/null)"
    expected=$(printf "\n\033[0;47m  \033[0;1;37m Hi, there!\033[0m\n\n")
    assertEquals "$expected" "$actual"
}

xtest_inform() {
    actual="$(./krab stdio-inform 'Hi, there!' 2>&1 > /dev/null)"
    expected=$(printf "\n\033[0;46m  \033[0;1;36m Hi, there!\033[0m\n\n")
    assertEquals "$expected" "$actual"
}

xtest_confirm() {
    actual="$(./krab stdio-confirm 'Hi, there!' 2>&1 > /dev/null)"
    expected=$(printf "\n\033[0;42m  \033[0;1;32m Hi, there!\033[0m\n\n")
    assertEquals "$expected" "$actual"
}

xtest_alert() {
    actual="$(./krab stdio-alert 'Hi, there!' 2>&1 > /dev/null)"
    expected=$(printf "\n\033[0;41m  \033[0;1;31m Hi, there!\033[0m\n\n")
    assertEquals "$expected" "$actual"
}

. ./vendor/shunit2/shunit2