#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../.."

directories='./bin ./src/bash ./tests/bash'
for directory in $directories; do
    find "$directory" | while read -r file; do
        if [ ! -f "$file" ]; then
            continue
         fi
        shellcheck -x "$file"
    done
done
shellcheck -x "$0"
